### PR TITLE
Start GHA

### PR DESCRIPTION
**Pull request by jbusecke**
This PR is aiming to transition the CI to github actions away from travis.

### CODE REVIEW

**Comment by jbusecke** [comment]
I am a bit confused why this workflow is not showing any activity at all. Will try to dig further in the coming days. If anybody has ideas how to debug this, they would be greatly appreciated.

**Comment by jbusecke** [comment]
Huh weird. All the sudden these showed up as if nothing happened. Oh well, github is weird sometimes...

**Comment by jbusecke** [comment]
Ok this looks pretty good, except the coverage report. Ill try to fix that and then I think we can switch the CI to github.

**Comment by rabernat** [comment]
Thanks Julius! This is great!

**Comment by jbusecke** [comment]
How do I kill Travis? I thought removing `travis.yml` would be enough?

**Comment by jbusecke** [comment]
I think this is ready to merge. We can probably also delete the travis webhook?

**Pull request merged**
