### PR TITLE
python 3 compatibility

### LINKED ISSUE #129: Python 3 support
It's long overdue

### LINKED ISSUE #130: Refactor travisci to support matrix builds
This is a necessary step towards #129.

A nice example of how it would work can be found here:
https://github.com/xgcm/xgcm/blob/master/.travis.yml

### PR DESCRIPTION
**Pull request by rabernat**
With this PR, the tests pass in python 2.7 and 3.5. There may still be some residual non-python 3 compliant code floating around, but we won't find it until we improve the tests.

Fixes #129
Fixes #130 

(I think this supercedes #138)

### CODE REVIEW

**Comment by rabernat** [comment]
@crocha700, as you can see from the [travis-ci build](https://travis-ci.org/pyqg/pyqg/builds/118385837), this works with 2.7 and 3.5, both with and without pyfftw. I found an [anaconda channel](https://anaconda.org/nanshe/pyfftw) that hosts a python3.5-compatible pyfftw.

The only weird thing happening is that py.test doesn't seem to want to exit with python 3.5 and pyfftw, so [the travis-ci build](https://travis-ci.org/pyqg/pyqg/jobs/118385841) is still running, even though the tests complete successfully. I'm not sure how to fix that.

**Comment by rabernat** [comment]
Well I restarted the build and it worked fine. So might have just been a fluke.

We'll have to keep an eye on that issue.

**Comment by crocha700** [comment]
Thanks for making these changes @rabernat !

Could you please update [whatsnew](https://github.com/pyqg/pyqg/blob/master/docs/whats-new.rst) and  mention the anaconda channel you found in [installation](https://github.com/pyqg/pyqg/blob/master/docs/installation.rst)?

**Comment by rabernat** [comment]
Still having the same issue with the python 3.5 build. I wonder if it's a pyfftw issue. Doesn't happen with out pyfftw. 

I can also intermittently reproduce the problem on my laptop.

**Comment by rabernat** [comment]
I'm going to merge this and file a new issue about the hanging problem.

**Pull request merged**
