### PR TITLE
Update for compatibility with Python 3

### PR DESCRIPTION
**Pull request by pittwolfe**
Dict returns view not list (line 631). Incorrect parens on print statement (line 636).

### CODE REVIEW

**Comment by rabernat** [comment]
Thanks for this Chris! Unfortunately the `describe_diagnostics` function is not tested by our test suite, so we missed it when adding python 3 support way back in the day. 

Would you feel comfortable adding a basic test of that function? That would help avoid such problems in the future. Doesn't have to be fancy...just call the function to ensure it doesn't error and check that there is some reasonable output.

**Comment by pittwolfe** [comment]
Hi Ryan:

I don’t mind writing a test, but I’m not up on this whole test-based development thing. Can to point me to a basic reference for the proper format of the test and how to get it included in the testing?

Cheers,
Christopher

**Comment by rabernat** [comment]
To run the test suite, you run
```
py.test -v pyqg
```
from the base directory. (You may have to `pip install pytest` first.) This is automatically run by [travis-CI](https://travis-ci.org/pyqg/pyqg) for every pull request.

To add a new test, first look at the existing tests and then add a method to one of the test classes. (The tests are not super well organized or consistent, but at least we have them.) I would recommend adding a method called `test_describe_diagnostics` to `PyqgModelTester` here:
https://github.com/pyqg/pyqg/blob/master/pyqg/tests/test_model.py

**Comment by rabernat** [comment]
Alternatively, you could write a whole new test module called `test_diagnostics.py`. That might be better. We should eventually develop full test coverage for the diagnostics.

**Comment by pittwolfe** [comment]
Added a diagnostics test. Confirms that describe_diagnostics fails with current code but passes with my python3 branch modifications. They’re on two separate branches, so they’ll need to be merged.

Christopher

**Comment by rabernat** [comment]
Hi Christopher! Thanks so much for taking the time to work on this. We sincerely appreciate your contribution.

I would like to clarify how the pull request process typically works for open source projects on github, including pyqg. It is rare for a pull request to be approved straight away in its original form. Most often, the maintainers have some feedback and request some changes (kind of like a paper review). This is what I did in my comment above (https://github.com/pyqg/pyqg/pull/168#issuecomment-373469471). 

The process for addressing these comments is the following:
- Make the requested changes to your local branch (in this case, your local branch is called `python3`)
- Run the test suite again locally
- Push the branch again to origin (`git push python3 origin`)

This will trigger the pull request here on github to be automatically updated and the Travis-CI tests to be run again.

Instead, you opened a new pull request (#169). There is no way to merge two pull requests together from github. And I can't tell a-priori whether they are actually compatible with each other. So it would really be better to have the new test that you wrote in #169 as part is *this* pull request.

To accomplish this, you could either merge the branches locally
- `git checkout python 3; git merge test_diagnostics`
or
- just copy the file `pyqg/tests/test_diagnostics.py` and add it directly to the `python3` branch

Then `git commit` and `git push python3 origin`.

Once you master this process, you will feel confident to contribute to any open source project you wish. pyqg has been a great way for many of us, myself included, to learn about this process, so I hope you see it as an educational experience (rather than a tedious one).

**Comment by rabernat** [comment]
Great! And new we can see that the tests are passing on Travis!

**Pull request merged**
