### PR TITLE
Navid docs

### LINKED ISSUE #210: Rollback removed Navid's doc fixes (#203)
The most recent rollback attempt appears to have wiped out Navid's doc fixes (from pull request #203), committed just 16 hours ago. Maybe the easiest thing is for him to resubmit the pull request.

### PR DESCRIPTION
**Pull request by rabernat**
My attempt to bring #203 back.

Closes #210.

@pittwolfe - have a look at this and see if you can find any inconsistencies.

### CODE REVIEW

**Comment by pittwolfe** [comment]
Everything looks good except commit 9175f6d, which gives the sizes of the background flow arrays consistent with the now-defunct 'zonal-jet' case.

**Comment by rabernat** [comment]
@pittwolfe - I just invited you to become an owner of the project. Once you accept, you should be able to edit the PR directly and make any fixes you see fit.

**Comment by pittwolfe** [comment]
It's weird. I seem to be able to edit the comments in the pull request and comment on the individual lines in the commits, but when I click 'edit', it just takes me to the original file in *your* repository (not Navid's updated file). I suspect I'm doing something wrong here ...

**Comment by rabernat** [comment]
Yes, it takes you to the branch whence the PR originates: `rabernat:navid-docs`. Edit those and the PR will update.

**Pull request merged**
