### PR TITLE
refactoring travisci build with python 3 tests

### LINKED ISSUE #130: Refactor travisci to support matrix builds
This is a necessary step towards #129.

A nice example of how it would work can be found here:
https://github.com/xgcm/xgcm/blob/master/.travis.yml

### PR DESCRIPTION
**Pull request by rabernat**
A sample build with the new setup:
https://travis-ci.org/rabernat/pyqg/builds/118349708

fixes #130 

updated channel specification
trying with and without pyfftw
hack to skip tests that rely on pyfftw
got rid of unnecessary import test
added missing yaml files
fix setup.py print statements
try to make test skipping work
fixing of setup.py strings for python 3

### CODE REVIEW

**Comment by rabernat** [comment]
The travis CI builds will continue to fail globally until python 3 support is in place. However, if you look into the [build matrix](https://travis-ci.org/pyqg/pyqg/builds/118351402), you can see that python 2.7 is passing (both with and without pyfftw).

**Comment by rabernat** [comment]
cc: @crocha700 -- review and merge when you can

**Comment by crocha700** [comment]
As far as I can tell this looks good to merge. Just one question: does pyfftw works with anaconda python 3.5? [I remember trying a while ago and failing](https://github.com/pyFFTW/pyFFTW/issues/71)...

**Comment by rabernat** [comment]
Don't merge this. I went farther with #139.

**Pull request closed without merging**
