### PR TITLE
Increase minimum wavenumber in calc_ispec to avoid large-lengthscale artifacts

### PR DESCRIPTION
**Pull request by asross**
See https://github.com/pyqg/pyqg/issues/272.

### CODE REVIEW

**Comment by rabernat** [comment]
Hi @asross - thanks so much for this!

It looks this area of the code is not currently covered by tests 😬. Would you be willing to perhaps add a quick test that covers the `calc_ispec` function? That way we could have a lot more confidence going forward that this feature will continue to work.

You could either add it to https://github.com/pyqg/pyqg/blob/master/pyqg/tests/test_reference_solns.py or else create a new test module (e.g. `test_diagnostic_tools.py`).

If you don't have time for this, we can still merge it as-is.

**Comment by asross** [comment]
Yep, will do -- it might take a week or two, but I agree it's important to test this area. Hopefully I can even write a test with a function whose isotropic spectrum has ground-truth values, and demonstrate that this minimum wavenumber is necessary to accurately compute it.

**Comment by rabernat** [comment]
Sounds good. I would say that _any_ test is better than no test. There are two separate tests being discussed:
- Whether the function actually works and does what it says it will do (my hope for this PR)
- Whether the model simulates and expected spectrum (what you proposed above) -- this is more of a "verification test" for the model than a test of the new feature itself (and is therefore a lower priority for me)

**Comment by asross** [comment]
Added a basic test that the isotropic spectrum peaks in the right place for a periodic function of known frequency!

**Pull request merged**
