### PR TITLE
[WIP] require pyfftw

### PR DESCRIPTION
**Pull request by rabernat**
Now that pyfftw is easily installed from conda, I think we can just require it as a dependency. This allows us to simplify the kernel.

### CODE REVIEW

**Comment by MFJansen** [comment]
I'm personally not a big fan of this. Not everyone uses conda, and it would be nice to make sure that students can easily download and use pyqg no matter what python installation they are using. (Just my two cents. If others agree that this is the way we want to go, I won't make a scene...)

**Comment by rabernat** [comment]
I don't propose merging this right away. It's part of a larger discussion #215, which would involve writing other kernels, including a pure numpy one.

I released pyqg v0.3.0 over the weekend, which should have all of our latest fixes / rollbacks. That  is a stable version which people can continue to use as you describe.

**Comment by MFJansen** [comment]
Sounds good! Thanks!

**Comment by rabernat** [comment]
Note that we are now requiring pyfftw as part of the packaging update in #278.

**Comment by asross** [comment]
It should still be possible to run pyqg without it if you install manually, but pyfftw is now the default for a pip install, which seems to work pretty smoothly. Probably makes sense to close this PR for now :)

**Pull request closed without merging**
