### PR TITLE
Fixes bug in logger

### PR DESCRIPTION
**Pull request by crocha700**

### CODE REVIEW

**Comment by crocha700** [comment]
Not sure why "test_particles" is no longer passing – I have only changed a small little thing in "_initialize_logger()"...

Any ideas?

**Comment by crocha700** [comment]
@rabernat do you have any thoughts on why "test_particles.py" does not pass on travis?

It passes here on my machine:

```{python}
crocha (multi_layer) tests $ python test_particles.py 
Vendor:  Continuum Analytics, Inc.
Package: mkl
Message: trial mode expires in 29 days
Vendor:  Continuum Analytics, Inc.
Package: mkl
Message: trial mode expires in 29 days
Vendor:  Continuum Analytics, Inc.
Package: mkl
Message: trial mode expires in 29 days
...
----------------------------------------------------------------------
Ran 3 tests in 1.613s

OK
````

**Comment by rabernat** [comment]
The test is failing because travis can't import scipy.
```
  File "/home/travis/build/pyqg/pyqg/pyqg/particles.py", line 217, in interpolate_gridded_scalar
    return scipy.ndimage.map_coordinates(cp, [j,i],
NameError: global name 'scipy' is not defined
```
I am confused why this just appeared now though.

**Comment by rabernat** [comment]
Correction, travis does have scipy available:
https://travis-ci.org/pyqg/pyqg/builds/84847833#L233

However, it isn't being imported properly. Could it be related to this commit?
https://github.com/crocha700/pyqg/commit/80bd5cc582118a63848611238e995fea8fc92565

**Comment by rabernat** [comment]
This is the relevant import
https://github.com/pyqg/pyqg/blob/develop/pyqg/particles.py#L9

**Comment by rabernat** [comment]
Ok so this is just a theory, but it might be because the default numpy version changed. Compare this passing build:
https://travis-ci.org/pyqg/pyqg/builds/83742858#L212

With this failing one:
https://travis-ci.org/pyqg/pyqg/builds/84847833#L214

Numpy changed from 1.9 to 1.10. 

Then in the failing build, we get this error:
```
RuntimeError: module compiled against API version a but this version of numpy is 9
```
https://travis-ci.org/pyqg/pyqg/builds/84847833#L338

I am guessing that we need to be more specific about the package versions in our travis.yml file:
https://github.com/pyqg/pyqg/blob/develop/.travis.yml#L24

**Comment by crocha700** [comment]
It's not related to 80bd5cc  --- I was just trying to make it pass in that commit...didn't work.

**Comment by rabernat** [comment]
Oops! This is now in conflict with the PR I just merged! So sorry, I didn't realize you were working on it at the same time.

**Comment by crocha700** [comment]
No prob. I'll try to rebase and resolve this conflict. You can merge that into master.

**Comment by rabernat** [comment]
I'll leave it to you to sort out however you prefer. We found the problem anyway.

**Comment by crocha700** [comment]
Sure. Thanks for the help!

**Pull request merged**
