### PR TITLE
Add diagnostic variables to xarray dataset

### PR DESCRIPTION
**Pull request by hscannell**
This PR adds available diagnostic variables to the output of the xarray dataset when calling `m.to_dataset()`. 

The following diagnostics are added if available:

- APEflux
- APEgen
- APEgenspec
- EKE
- EKEdiss
- Ensspec
- KEflux
- KEspec
- entspec

### CODE REVIEW

**Comment by rabernat** [comment]
Thanks for getting this started Hillary!

As I mentioned in #238, I think the right approach is to refactor how diagnostics work in `model.py` first. I don't think we should be putting metadata about diagnostics in `xarray_output.py`.

**Comment by hscannell** [comment]
I'm not sure I complete understand #238, but I look forward to chatting about it more during our meeting this morning.
Having the diagnostics in the dataset has been pretty helpful when saving diagnostics at intermediate time steps with `run_with_snapshots`. 

Screen Shot 2021-05-07 at 8 25 49 AM

**Comment by hscannell** [comment]
This PR should close #235

**Comment by hscannell** [comment]
Closing this for now after our discussion about #238.

**Pull request closed without merging**
