### PR TITLE
Fixes bug: now computes diagnostics after tavestart

### PR DESCRIPTION
**Pull request by crocha700**

### CODE REVIEW

**Comment by crocha700** [comment]
@rabernat: who can I publish this fixed into the release? Also, the SQG docs is not currently in http://pyqg.readthedocs.org/en/stable/

**Comment by rabernat** [comment]
> who can I publish this fixed into the release?

I really don't understand the question.

> the SQG docs is not currently in...

You have to look at the latest (rather than stable) docs:
http://pyqg.readthedocs.org/en/latest/

**Comment by crocha700** [comment]
I mean, how to add that small fix to: http://pyqg.readthedocs.org/en/latest/whats-new.html

Maybe this is not necessary...

**Comment by rabernat** [comment]
Absolutely! Let's keep track of all changes there.

We don't necessarily have to release a new version just yet. We can accumulate bug fixes for a while longer if we want. But let's definitely document them.

**Comment by rabernat** [comment]
@crocha700 - add a note to the what's new docs and then we can merge this.

**Comment by rabernat** [comment]
Wait you already merged...sorry I was confused.

In the future, put a note in docs/whats-new.rst to explain what changes were made in the PR.

**Comment by crocha700** [comment]
Sorry, I merged after it passed the tests. I'll do this in the next PR.

**Pull request merged**
